language: node_js
node_js:
- lts/*
before_script:
- npm install grunt-cli -g
deploy:
  provider: npm
  email: dmitry@itis.cs.msu.ru
  skip_cleanup: true
  api_key:
    secure: i8AuRI2bfMHX48bupyuibpQQMzORV9gZugeW3SJaStMJAGt1uAn2fei4V6XKmBzl1EOesyk4cp8bg8kZPTAFRyxADHo545mVA57hu+vfiHwUtYYbf8BH3TyS9AiOKjzgR0OUJNjy92EjqkrtAKkaEr3W4pTkTTF2881NOGrcVMYziubpvPt7fN4moJElnVW0855MHksE1XfvKzdshwps4jOhp3NfIN+eKIEV+R5/xPwFnhXJaLh/6/MfI21qFiMISlrYl7nCWDDlU5ADRUSa7Xyc17wGvX3j7hG7OtE1Dx3gkxVE4L/lOfV/5V2owi73AUHijLEJB1Ty3t0hXG3JuoJR1k7U3EKMbyIG2mkR5T2yPQRwNNj7l7YJg7sP2TjAv0T8xIhYJLJsmeIVSvsBzY8oK4W2QiNqEmEkHpUNgkqf4EdhAWF7I+b2mFOUcSDHMglTWShRp5oX6vQfox9eAGjwtpVzJP8Kn2Zp16jdRo3xSEAFUbHuklR3OZHZzrQJQjYYo6xSG/zbvRQvx5Ei3EavcInfunzfJqldGMT0z8GrnAApnDiAGwlfTSF4B/8buQMcv4vp1UFAqilwLOcuB6jxRSSORiEqV+aKOlNJ/7d7pVYHyMaDXwHZDIk70R07qXuyihUm+JuhMBVGZ9TofljzYQgwINeXkRrF/HCQ9es=
  on:
    tags: true
